# Generated by Django 3.0.5 on 2020-04-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'คณิตศาสตร์'), ('Sci', 'วิทยาศาสตร์'), ('Art', 'ศิลปะ'), ('Music', 'ดนตรี'), ('Physics', 'ฟิสิกส์')], default='math', max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('student_last', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
